production:
  pid_file: /var/www/kursor/shared/tmp/searchd.pid
  searchd_file_path: /var/www/kursor/shared/db/sphinx
  charset_type: utf-8
  enable_star: true
  html_strip: true

development:
  charset_type: utf-8
  enable_star: true
  html_strip: true
